// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ygggigzbcvosjpmrywck.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlnZ2dpZ3piY3Zvc2pwbXJ5d2NrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzNzcxODYsImV4cCI6MjA2Njk1MzE4Nn0.0lQOk7MyecssJYorFeLiq03a6iZJpvedcjVEpNkDJLU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});